name: geohexviz
channels:
  - conda-forge
  - defaults
  - plotly
dependencies:
  - geopandas
  - shapely
  - setuptools
  - pyproj
  - python-kaleido
  - geojson
  - plotly
  - h3
  - pyyaml
  - rtree