package:
  name: "geohexviz"
  version: "1.0.0"

source:
  git_rev: v1.0.0
  git_url: https://github.com/wino6687/SWEpy

requirements:
  host:
    - python
    - setuptools
  build:
    - python
  run:
    - python
    - gdal
    - fiona
    - pandas
    - shapely
    - numpy
    - geopandas
    - h3-py

about:
  home: https://github.com/wino6687/SWEpy
  license: MIT
  license_familY: MIT
  license_file: LICENSE
  summary: "A library for the visualization of hexagonally binned data sets."

extra:
  recipe-maintainers:
    - tony_zeidan